### ISSUE TITLE
The colors are not readable they are like black sometimes on replit

### ISSUE THREAD

**Issue by nichevulcan20** [ItzBoiz/advanced-server-nuker#1]
please update the look of colors to readable colors not like unreadable like the magenta on black looks so dark  on replit please fix it.

**Comment by ItzBoiz** [comment]
I have made the colors readable now, now they are
- Red (for faliure)
- Green (for sucess)
- Blue (for information)

To make the changes visible, please re-download the project!

**Comment by nichevulcan20** [comment]
Yesss now good
